/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gov.pagopa.paymentupdater.dto.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Kafka JS schema for cosmos api container 'message-status' */
@org.apache.avro.specific.AvroGenerated
public class messageStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4851212653284355445L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"messageStatus\",\"namespace\":\"it.gov.pagopa.reminder.dto\",\"doc\":\"Kafka JS schema for cosmos api container 'message-status'\",\"fields\":[{\"name\":\"op\",\"type\":{\"type\":\"enum\",\"name\":\"MessageStatusCrudOperation\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}},{\"name\":\"id\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"messageId\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"version\",\"type\":\"int\",\"default\":0},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"MessageStatusDescription\",\"symbols\":[\"ACCEPTED\",\"THROTTLED\",\"FAILED\",\"PROCESSED\",\"REJECTED\"]}},{\"name\":\"isRead\",\"type\":\"boolean\",\"default\":false},{\"name\":\"isArchived\",\"type\":\"boolean\",\"default\":false},{\"name\":\"timestamp\",\"type\":\"long\",\"default\":0,\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation op;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence messageId;
  @Deprecated public int version;
  @Deprecated public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription status;
  @Deprecated public boolean isRead;
  @Deprecated public boolean isArchived;
  @Deprecated public long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public messageStatus() {}

  /**
   * All-args constructor.
   * @param op The new value for op
   * @param id The new value for id
   * @param messageId The new value for messageId
   * @param version The new value for version
   * @param status The new value for status
   * @param isRead The new value for isRead
   * @param isArchived The new value for isArchived
   * @param timestamp The new value for timestamp
   */
  public messageStatus(it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation op, java.lang.CharSequence id, java.lang.CharSequence messageId, java.lang.Integer version, it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription status, java.lang.Boolean isRead, java.lang.Boolean isArchived, java.lang.Long timestamp) {
    this.op = op;
    this.id = id;
    this.messageId = messageId;
    this.version = version;
    this.status = status;
    this.isRead = isRead;
    this.isArchived = isArchived;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return op;
    case 1: return id;
    case 2: return messageId;
    case 3: return version;
    case 4: return status;
    case 5: return isRead;
    case 6: return isArchived;
    case 7: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: op = (it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    case 2: messageId = (java.lang.CharSequence)value$; break;
    case 3: version = (java.lang.Integer)value$; break;
    case 4: status = (it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription)value$; break;
    case 5: isRead = (java.lang.Boolean)value$; break;
    case 6: isArchived = (java.lang.Boolean)value$; break;
    case 7: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'op' field.
   * @return The value of the 'op' field.
   */
  public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation getOp() {
    return op;
  }

  /**
   * Sets the value of the 'op' field.
   * @param value the value to set.
   */
  public void setOp(it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation value) {
    this.op = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'messageId' field.
   * @return The value of the 'messageId' field.
   */
  public java.lang.CharSequence getMessageId() {
    return messageId;
  }

  /**
   * Sets the value of the 'messageId' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.CharSequence value) {
    this.messageId = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.Integer getVersion() {
    return version;
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Integer value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'isRead' field.
   * @return The value of the 'isRead' field.
   */
  public java.lang.Boolean getIsRead() {
    return isRead;
  }

  /**
   * Sets the value of the 'isRead' field.
   * @param value the value to set.
   */
  public void setIsRead(java.lang.Boolean value) {
    this.isRead = value;
  }

  /**
   * Gets the value of the 'isArchived' field.
   * @return The value of the 'isArchived' field.
   */
  public java.lang.Boolean getIsArchived() {
    return isArchived;
  }

  /**
   * Sets the value of the 'isArchived' field.
   * @param value the value to set.
   */
  public void setIsArchived(java.lang.Boolean value) {
    this.isArchived = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new messageStatus RecordBuilder.
   * @return A new messageStatus RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder newBuilder() {
    return new it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder();
  }

  /**
   * Creates a new messageStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new messageStatus RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder newBuilder(it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder other) {
    return new it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder(other);
  }

  /**
   * Creates a new messageStatus RecordBuilder by copying an existing messageStatus instance.
   * @param other The existing instance to copy.
   * @return A new messageStatus RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder newBuilder(it.gov.pagopa.paymentupdater.dto.avro.messageStatus other) {
    return new it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder(other);
  }

  /**
   * RecordBuilder for messageStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<messageStatus>
    implements org.apache.avro.data.RecordBuilder<messageStatus> {

    private it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation op;
    private java.lang.CharSequence id;
    private java.lang.CharSequence messageId;
    private int version;
    private it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription status;
    private boolean isRead;
    private boolean isArchived;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.op)) {
        this.op = data().deepCopy(fields()[0].schema(), other.op);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.messageId)) {
        this.messageId = data().deepCopy(fields()[2].schema(), other.messageId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.version)) {
        this.version = data().deepCopy(fields()[3].schema(), other.version);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.isRead)) {
        this.isRead = data().deepCopy(fields()[5].schema(), other.isRead);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isArchived)) {
        this.isArchived = data().deepCopy(fields()[6].schema(), other.isArchived);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing messageStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gov.pagopa.paymentupdater.dto.avro.messageStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.op)) {
        this.op = data().deepCopy(fields()[0].schema(), other.op);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.messageId)) {
        this.messageId = data().deepCopy(fields()[2].schema(), other.messageId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.version)) {
        this.version = data().deepCopy(fields()[3].schema(), other.version);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.isRead)) {
        this.isRead = data().deepCopy(fields()[5].schema(), other.isRead);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isArchived)) {
        this.isArchived = data().deepCopy(fields()[6].schema(), other.isArchived);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'op' field.
      * @return The value.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation getOp() {
      return op;
    }

    /**
      * Sets the value of the 'op' field.
      * @param value The value of 'op'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setOp(it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation value) {
      validate(fields()[0], value);
      this.op = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'op' field has been set.
      * @return True if the 'op' field has been set, false otherwise.
      */
    public boolean hasOp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'op' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearOp() {
      op = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'messageId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageId() {
      return messageId;
    }

    /**
      * Sets the value of the 'messageId' field.
      * @param value The value of 'messageId'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setMessageId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.messageId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'messageId' field has been set.
      * @return True if the 'messageId' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'messageId' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearMessageId() {
      messageId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.Integer getVersion() {
      return version;
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setVersion(int value) {
      validate(fields()[3], value);
      this.version = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearVersion() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setStatus(it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'isRead' field.
      * @return The value.
      */
    public java.lang.Boolean getIsRead() {
      return isRead;
    }

    /**
      * Sets the value of the 'isRead' field.
      * @param value The value of 'isRead'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setIsRead(boolean value) {
      validate(fields()[5], value);
      this.isRead = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'isRead' field has been set.
      * @return True if the 'isRead' field has been set, false otherwise.
      */
    public boolean hasIsRead() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'isRead' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearIsRead() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'isArchived' field.
      * @return The value.
      */
    public java.lang.Boolean getIsArchived() {
      return isArchived;
    }

    /**
      * Sets the value of the 'isArchived' field.
      * @param value The value of 'isArchived'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setIsArchived(boolean value) {
      validate(fields()[6], value);
      this.isArchived = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'isArchived' field has been set.
      * @return True if the 'isArchived' field has been set, false otherwise.
      */
    public boolean hasIsArchived() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'isArchived' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearIsArchived() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder setTimestamp(long value) {
      validate(fields()[7], value);
      this.timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.messageStatus.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public messageStatus build() {
      try {
        messageStatus record = new messageStatus();
        record.op = fieldSetFlags()[0] ? this.op : (it.gov.pagopa.paymentupdater.dto.avro.MessageStatusCrudOperation) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.messageId = fieldSetFlags()[2] ? this.messageId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.version = fieldSetFlags()[3] ? this.version : (java.lang.Integer) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (it.gov.pagopa.paymentupdater.dto.avro.MessageStatusDescription) defaultValue(fields()[4]);
        record.isRead = fieldSetFlags()[5] ? this.isRead : (java.lang.Boolean) defaultValue(fields()[5]);
        record.isArchived = fieldSetFlags()[6] ? this.isArchived : (java.lang.Boolean) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
