/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gov.pagopa.paymentupdater.dto.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MessageContentType {
  GENERIC, PAYMENT, EU_COVID_CERT, LEGAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageContentType\",\"namespace\":\"it.gov.pagopa.reminder.dto\",\"symbols\":[\"GENERIC\",\"PAYMENT\",\"EU_COVID_CERT\",\"LEGAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
