/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gov.pagopa.paymentupdater.dto.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Kafka JS schema for cosmos api container 'messages' */
@org.apache.avro.specific.AvroGenerated
public class message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8716586153299971923L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"message\",\"namespace\":\"it.gov.pagopa.reminder.dto\",\"doc\":\"Kafka JS schema for cosmos api container 'messages'\",\"fields\":[{\"name\":\"op\",\"type\":{\"type\":\"enum\",\"name\":\"MessageCrudOperation\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}},{\"name\":\"id\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"senderServiceId\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"senderUserId\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"timeToLiveSeconds\",\"type\":\"int\",\"default\":3600},{\"name\":\"createdAt\",\"type\":\"long\",\"default\":0,\"logicalType\":\"timestamp-millis\"},{\"name\":\"isPending\",\"type\":\"boolean\",\"default\":true},{\"name\":\"content_subject\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"content_type\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"MessageContentType\",\"symbols\":[\"GENERIC\",\"PAYMENT\",\"EU_COVID_CERT\",\"LEGAL\"]}],\"default\":null},{\"name\":\"content_paymentData_amount\",\"type\":\"int\",\"default\":0},{\"name\":\"content_paymentData_noticeNumber\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"content_paymentData_invalidAfterDueDate\",\"type\":\"boolean\",\"default\":false},{\"name\":\"content_paymentData_payeeFiscalCode\",\"type\":\"string\",\"default\":\"undefined\"},{\"name\":\"timestamp\",\"type\":\"long\",\"default\":0,\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation op;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence senderServiceId;
  @Deprecated public java.lang.CharSequence senderUserId;
  @Deprecated public int timeToLiveSeconds;
  @Deprecated public long createdAt;
  @Deprecated public boolean isPending;
  @Deprecated public java.lang.CharSequence content_subject;
  @Deprecated public it.gov.pagopa.paymentupdater.dto.avro.MessageContentType content_type;
  @Deprecated public int content_paymentData_amount;
  @Deprecated public java.lang.CharSequence content_paymentData_noticeNumber;
  @Deprecated public boolean content_paymentData_invalidAfterDueDate;
  @Deprecated public java.lang.CharSequence content_paymentData_payeeFiscalCode;
  @Deprecated public long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public message() {}
  
  public message(java.lang.CharSequence id, it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation op) {
  	this.op = op;
    this.id = id;
  }

  /**
   * All-args constructor.
   * @param op The new value for op
   * @param id The new value for id
   * @param senderServiceId The new value for senderServiceId
   * @param senderUserId The new value for senderUserId
   * @param timeToLiveSeconds The new value for timeToLiveSeconds
   * @param createdAt The new value for createdAt
   * @param isPending The new value for isPending
   * @param content_subject The new value for content_subject
   * @param content_type The new value for content_type
   * @param content_paymentData_amount The new value for content_paymentData_amount
   * @param content_paymentData_noticeNumber The new value for content_paymentData_noticeNumber
   * @param content_paymentData_invalidAfterDueDate The new value for content_paymentData_invalidAfterDueDate
   * @param content_paymentData_payeeFiscalCode The new value for content_paymentData_payeeFiscalCode
   * @param timestamp The new value for timestamp
   */
  public message(it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation op, java.lang.CharSequence id, java.lang.CharSequence senderServiceId, java.lang.CharSequence senderUserId, java.lang.Integer timeToLiveSeconds, java.lang.Long createdAt, java.lang.Boolean isPending, java.lang.CharSequence content_subject, it.gov.pagopa.paymentupdater.dto.avro.MessageContentType content_type, java.lang.Integer content_paymentData_amount, java.lang.CharSequence content_paymentData_noticeNumber, java.lang.Boolean content_paymentData_invalidAfterDueDate, java.lang.CharSequence content_paymentData_payeeFiscalCode, java.lang.Long timestamp) {
    this.op = op;
    this.id = id;
    this.senderServiceId = senderServiceId;
    this.senderUserId = senderUserId;
    this.timeToLiveSeconds = timeToLiveSeconds;
    this.createdAt = createdAt;
    this.isPending = isPending;
    this.content_subject = content_subject;
    this.content_type = content_type;
    this.content_paymentData_amount = content_paymentData_amount;
    this.content_paymentData_noticeNumber = content_paymentData_noticeNumber;
    this.content_paymentData_invalidAfterDueDate = content_paymentData_invalidAfterDueDate;
    this.content_paymentData_payeeFiscalCode = content_paymentData_payeeFiscalCode;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return op;
    case 1: return id;
    case 2: return senderServiceId;
    case 3: return senderUserId;
    case 4: return timeToLiveSeconds;
    case 5: return createdAt;
    case 6: return isPending;
    case 7: return content_subject;
    case 8: return content_type;
    case 9: return content_paymentData_amount;
    case 10: return content_paymentData_noticeNumber;
    case 11: return content_paymentData_invalidAfterDueDate;
    case 12: return content_paymentData_payeeFiscalCode;
    case 13: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: op = (it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    case 2: senderServiceId = (java.lang.CharSequence)value$; break;
    case 3: senderUserId = (java.lang.CharSequence)value$; break;
    case 4: timeToLiveSeconds = (java.lang.Integer)value$; break;
    case 5: createdAt = (java.lang.Long)value$; break;
    case 6: isPending = (java.lang.Boolean)value$; break;
    case 7: content_subject = (java.lang.CharSequence)value$; break;
    case 8: content_type = (it.gov.pagopa.paymentupdater.dto.avro.MessageContentType)value$; break;
    case 9: content_paymentData_amount = (java.lang.Integer)value$; break;
    case 10: content_paymentData_noticeNumber = (java.lang.CharSequence)value$; break;
    case 11: content_paymentData_invalidAfterDueDate = (java.lang.Boolean)value$; break;
    case 12: content_paymentData_payeeFiscalCode = (java.lang.CharSequence)value$; break;
    case 13: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'op' field.
   * @return The value of the 'op' field.
   */
  public it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation getOp() {
    return op;
  }

  /**
   * Sets the value of the 'op' field.
   * @param value the value to set.
   */
  public void setOp(it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation value) {
    this.op = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'senderServiceId' field.
   * @return The value of the 'senderServiceId' field.
   */
  public java.lang.CharSequence getSenderServiceId() {
    return senderServiceId;
  }

  /**
   * Sets the value of the 'senderServiceId' field.
   * @param value the value to set.
   */
  public void setSenderServiceId(java.lang.CharSequence value) {
    this.senderServiceId = value;
  }

  /**
   * Gets the value of the 'senderUserId' field.
   * @return The value of the 'senderUserId' field.
   */
  public java.lang.CharSequence getSenderUserId() {
    return senderUserId;
  }

  /**
   * Sets the value of the 'senderUserId' field.
   * @param value the value to set.
   */
  public void setSenderUserId(java.lang.CharSequence value) {
    this.senderUserId = value;
  }

  /**
   * Gets the value of the 'timeToLiveSeconds' field.
   * @return The value of the 'timeToLiveSeconds' field.
   */
  public java.lang.Integer getTimeToLiveSeconds() {
    return timeToLiveSeconds;
  }

  /**
   * Sets the value of the 'timeToLiveSeconds' field.
   * @param value the value to set.
   */
  public void setTimeToLiveSeconds(java.lang.Integer value) {
    this.timeToLiveSeconds = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.Long getCreatedAt() {
    return createdAt;
  }

  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.Long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'isPending' field.
   * @return The value of the 'isPending' field.
   */
  public java.lang.Boolean getIsPending() {
    return isPending;
  }

  /**
   * Sets the value of the 'isPending' field.
   * @param value the value to set.
   */
  public void setIsPending(java.lang.Boolean value) {
    this.isPending = value;
  }

  /**
   * Gets the value of the 'content_subject' field.
   * @return The value of the 'content_subject' field.
   */
  public java.lang.CharSequence getContentSubject() {
    return content_subject;
  }

  /**
   * Sets the value of the 'content_subject' field.
   * @param value the value to set.
   */
  public void setContentSubject(java.lang.CharSequence value) {
    this.content_subject = value;
  }

  /**
   * Gets the value of the 'content_type' field.
   * @return The value of the 'content_type' field.
   */
  public it.gov.pagopa.paymentupdater.dto.avro.MessageContentType getContentType() {
    return content_type;
  }

  /**
   * Sets the value of the 'content_type' field.
   * @param value the value to set.
   */
  public void setContentType(it.gov.pagopa.paymentupdater.dto.avro.MessageContentType value) {
    this.content_type = value;
  }

  /**
   * Gets the value of the 'content_paymentData_amount' field.
   * @return The value of the 'content_paymentData_amount' field.
   */
  public java.lang.Integer getContentPaymentDataAmount() {
    return content_paymentData_amount;
  }

  /**
   * Sets the value of the 'content_paymentData_amount' field.
   * @param value the value to set.
   */
  public void setContentPaymentDataAmount(java.lang.Integer value) {
    this.content_paymentData_amount = value;
  }

  /**
   * Gets the value of the 'content_paymentData_noticeNumber' field.
   * @return The value of the 'content_paymentData_noticeNumber' field.
   */
  public java.lang.CharSequence getContentPaymentDataNoticeNumber() {
    return content_paymentData_noticeNumber;
  }

  /**
   * Sets the value of the 'content_paymentData_noticeNumber' field.
   * @param value the value to set.
   */
  public void setContentPaymentDataNoticeNumber(java.lang.CharSequence value) {
    this.content_paymentData_noticeNumber = value;
  }

  /**
   * Gets the value of the 'content_paymentData_invalidAfterDueDate' field.
   * @return The value of the 'content_paymentData_invalidAfterDueDate' field.
   */
  public java.lang.Boolean getContentPaymentDataInvalidAfterDueDate() {
    return content_paymentData_invalidAfterDueDate;
  }

  /**
   * Sets the value of the 'content_paymentData_invalidAfterDueDate' field.
   * @param value the value to set.
   */
  public void setContentPaymentDataInvalidAfterDueDate(java.lang.Boolean value) {
    this.content_paymentData_invalidAfterDueDate = value;
  }

  /**
   * Gets the value of the 'content_paymentData_payeeFiscalCode' field.
   * @return The value of the 'content_paymentData_payeeFiscalCode' field.
   */
  public java.lang.CharSequence getContentPaymentDataPayeeFiscalCode() {
    return content_paymentData_payeeFiscalCode;
  }

  /**
   * Sets the value of the 'content_paymentData_payeeFiscalCode' field.
   * @param value the value to set.
   */
  public void setContentPaymentDataPayeeFiscalCode(java.lang.CharSequence value) {
    this.content_paymentData_payeeFiscalCode = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new message RecordBuilder.
   * @return A new message RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.message.Builder newBuilder() {
    return new it.gov.pagopa.paymentupdater.dto.avro.message.Builder();
  }

  /**
   * Creates a new message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new message RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.message.Builder newBuilder(it.gov.pagopa.paymentupdater.dto.avro.message.Builder other) {
    return new it.gov.pagopa.paymentupdater.dto.avro.message.Builder(other);
  }

  /**
   * Creates a new message RecordBuilder by copying an existing message instance.
   * @param other The existing instance to copy.
   * @return A new message RecordBuilder
   */
  public static it.gov.pagopa.paymentupdater.dto.avro.message.Builder newBuilder(it.gov.pagopa.paymentupdater.dto.avro.message other) {
    return new it.gov.pagopa.paymentupdater.dto.avro.message.Builder(other);
  }

  /**
   * RecordBuilder for message instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<message>
    implements org.apache.avro.data.RecordBuilder<message> {

    private it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation op;
    private java.lang.CharSequence id;
    private java.lang.CharSequence senderServiceId;
    private java.lang.CharSequence senderUserId;
    private int timeToLiveSeconds;
    private long createdAt;
    private boolean isPending;
    private java.lang.CharSequence content_subject;
    private it.gov.pagopa.paymentupdater.dto.avro.MessageContentType content_type;
    private int content_paymentData_amount;
    private java.lang.CharSequence content_paymentData_noticeNumber;
    private boolean content_paymentData_invalidAfterDueDate;
    private java.lang.CharSequence content_paymentData_payeeFiscalCode;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(it.gov.pagopa.paymentupdater.dto.avro.message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.op)) {
        this.op = data().deepCopy(fields()[0].schema(), other.op);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.senderServiceId)) {
        this.senderServiceId = data().deepCopy(fields()[2].schema(), other.senderServiceId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.senderUserId)) {
        this.senderUserId = data().deepCopy(fields()[3].schema(), other.senderUserId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timeToLiveSeconds)) {
        this.timeToLiveSeconds = data().deepCopy(fields()[4].schema(), other.timeToLiveSeconds);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isPending)) {
        this.isPending = data().deepCopy(fields()[6].schema(), other.isPending);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.content_subject)) {
        this.content_subject = data().deepCopy(fields()[7].schema(), other.content_subject);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.content_type)) {
        this.content_type = data().deepCopy(fields()[8].schema(), other.content_type);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.content_paymentData_amount)) {
        this.content_paymentData_amount = data().deepCopy(fields()[9].schema(), other.content_paymentData_amount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.content_paymentData_noticeNumber)) {
        this.content_paymentData_noticeNumber = data().deepCopy(fields()[10].schema(), other.content_paymentData_noticeNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.content_paymentData_invalidAfterDueDate)) {
        this.content_paymentData_invalidAfterDueDate = data().deepCopy(fields()[11].schema(), other.content_paymentData_invalidAfterDueDate);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.content_paymentData_payeeFiscalCode)) {
        this.content_paymentData_payeeFiscalCode = data().deepCopy(fields()[12].schema(), other.content_paymentData_payeeFiscalCode);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[13].schema(), other.timestamp);
        fieldSetFlags()[13] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing message instance
     * @param other The existing instance to copy.
     */
    private Builder(it.gov.pagopa.paymentupdater.dto.avro.message other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.op)) {
        this.op = data().deepCopy(fields()[0].schema(), other.op);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.senderServiceId)) {
        this.senderServiceId = data().deepCopy(fields()[2].schema(), other.senderServiceId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.senderUserId)) {
        this.senderUserId = data().deepCopy(fields()[3].schema(), other.senderUserId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timeToLiveSeconds)) {
        this.timeToLiveSeconds = data().deepCopy(fields()[4].schema(), other.timeToLiveSeconds);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.isPending)) {
        this.isPending = data().deepCopy(fields()[6].schema(), other.isPending);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.content_subject)) {
        this.content_subject = data().deepCopy(fields()[7].schema(), other.content_subject);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.content_type)) {
        this.content_type = data().deepCopy(fields()[8].schema(), other.content_type);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.content_paymentData_amount)) {
        this.content_paymentData_amount = data().deepCopy(fields()[9].schema(), other.content_paymentData_amount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.content_paymentData_noticeNumber)) {
        this.content_paymentData_noticeNumber = data().deepCopy(fields()[10].schema(), other.content_paymentData_noticeNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.content_paymentData_invalidAfterDueDate)) {
        this.content_paymentData_invalidAfterDueDate = data().deepCopy(fields()[11].schema(), other.content_paymentData_invalidAfterDueDate);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.content_paymentData_payeeFiscalCode)) {
        this.content_paymentData_payeeFiscalCode = data().deepCopy(fields()[12].schema(), other.content_paymentData_payeeFiscalCode);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[13].schema(), other.timestamp);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'op' field.
      * @return The value.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation getOp() {
      return op;
    }

    /**
      * Sets the value of the 'op' field.
      * @param value The value of 'op'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setOp(it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation value) {
      validate(fields()[0], value);
      this.op = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'op' field has been set.
      * @return True if the 'op' field has been set, false otherwise.
      */
    public boolean hasOp() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'op' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearOp() {
      op = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderServiceId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderServiceId() {
      return senderServiceId;
    }

    /**
      * Sets the value of the 'senderServiceId' field.
      * @param value The value of 'senderServiceId'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setSenderServiceId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.senderServiceId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'senderServiceId' field has been set.
      * @return True if the 'senderServiceId' field has been set, false otherwise.
      */
    public boolean hasSenderServiceId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'senderServiceId' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearSenderServiceId() {
      senderServiceId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'senderUserId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSenderUserId() {
      return senderUserId;
    }

    /**
      * Sets the value of the 'senderUserId' field.
      * @param value The value of 'senderUserId'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setSenderUserId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.senderUserId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'senderUserId' field has been set.
      * @return True if the 'senderUserId' field has been set, false otherwise.
      */
    public boolean hasSenderUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'senderUserId' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearSenderUserId() {
      senderUserId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timeToLiveSeconds' field.
      * @return The value.
      */
    public java.lang.Integer getTimeToLiveSeconds() {
      return timeToLiveSeconds;
    }

    /**
      * Sets the value of the 'timeToLiveSeconds' field.
      * @param value The value of 'timeToLiveSeconds'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setTimeToLiveSeconds(int value) {
      validate(fields()[4], value);
      this.timeToLiveSeconds = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timeToLiveSeconds' field has been set.
      * @return True if the 'timeToLiveSeconds' field has been set, false otherwise.
      */
    public boolean hasTimeToLiveSeconds() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timeToLiveSeconds' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearTimeToLiveSeconds() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.Long getCreatedAt() {
      return createdAt;
    }

    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setCreatedAt(long value) {
      validate(fields()[5], value);
      this.createdAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'isPending' field.
      * @return The value.
      */
    public java.lang.Boolean getIsPending() {
      return isPending;
    }

    /**
      * Sets the value of the 'isPending' field.
      * @param value The value of 'isPending'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setIsPending(boolean value) {
      validate(fields()[6], value);
      this.isPending = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'isPending' field has been set.
      * @return True if the 'isPending' field has been set, false otherwise.
      */
    public boolean hasIsPending() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'isPending' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearIsPending() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getContentSubject() {
      return content_subject;
    }

    /**
      * Sets the value of the 'content_subject' field.
      * @param value The value of 'content_subject'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentSubject(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.content_subject = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'content_subject' field has been set.
      * @return True if the 'content_subject' field has been set, false otherwise.
      */
    public boolean hasContentSubject() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'content_subject' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentSubject() {
      content_subject = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_type' field.
      * @return The value.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.MessageContentType getContentType() {
      return content_type;
    }

    /**
      * Sets the value of the 'content_type' field.
      * @param value The value of 'content_type'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentType(it.gov.pagopa.paymentupdater.dto.avro.MessageContentType value) {
      validate(fields()[8], value);
      this.content_type = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'content_type' field has been set.
      * @return True if the 'content_type' field has been set, false otherwise.
      */
    public boolean hasContentType() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'content_type' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentType() {
      content_type = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_paymentData_amount' field.
      * @return The value.
      */
    public java.lang.Integer getContentPaymentDataAmount() {
      return content_paymentData_amount;
    }

    /**
      * Sets the value of the 'content_paymentData_amount' field.
      * @param value The value of 'content_paymentData_amount'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentPaymentDataAmount(int value) {
      validate(fields()[9], value);
      this.content_paymentData_amount = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'content_paymentData_amount' field has been set.
      * @return True if the 'content_paymentData_amount' field has been set, false otherwise.
      */
    public boolean hasContentPaymentDataAmount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'content_paymentData_amount' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentPaymentDataAmount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_paymentData_noticeNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getContentPaymentDataNoticeNumber() {
      return content_paymentData_noticeNumber;
    }

    /**
      * Sets the value of the 'content_paymentData_noticeNumber' field.
      * @param value The value of 'content_paymentData_noticeNumber'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentPaymentDataNoticeNumber(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.content_paymentData_noticeNumber = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'content_paymentData_noticeNumber' field has been set.
      * @return True if the 'content_paymentData_noticeNumber' field has been set, false otherwise.
      */
    public boolean hasContentPaymentDataNoticeNumber() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'content_paymentData_noticeNumber' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentPaymentDataNoticeNumber() {
      content_paymentData_noticeNumber = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_paymentData_invalidAfterDueDate' field.
      * @return The value.
      */
    public java.lang.Boolean getContentPaymentDataInvalidAfterDueDate() {
      return content_paymentData_invalidAfterDueDate;
    }

    /**
      * Sets the value of the 'content_paymentData_invalidAfterDueDate' field.
      * @param value The value of 'content_paymentData_invalidAfterDueDate'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentPaymentDataInvalidAfterDueDate(boolean value) {
      validate(fields()[11], value);
      this.content_paymentData_invalidAfterDueDate = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'content_paymentData_invalidAfterDueDate' field has been set.
      * @return True if the 'content_paymentData_invalidAfterDueDate' field has been set, false otherwise.
      */
    public boolean hasContentPaymentDataInvalidAfterDueDate() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'content_paymentData_invalidAfterDueDate' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentPaymentDataInvalidAfterDueDate() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'content_paymentData_payeeFiscalCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getContentPaymentDataPayeeFiscalCode() {
      return content_paymentData_payeeFiscalCode;
    }

    /**
      * Sets the value of the 'content_paymentData_payeeFiscalCode' field.
      * @param value The value of 'content_paymentData_payeeFiscalCode'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setContentPaymentDataPayeeFiscalCode(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.content_paymentData_payeeFiscalCode = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'content_paymentData_payeeFiscalCode' field has been set.
      * @return True if the 'content_paymentData_payeeFiscalCode' field has been set, false otherwise.
      */
    public boolean hasContentPaymentDataPayeeFiscalCode() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'content_paymentData_payeeFiscalCode' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearContentPaymentDataPayeeFiscalCode() {
      content_paymentData_payeeFiscalCode = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder setTimestamp(long value) {
      validate(fields()[13], value);
      this.timestamp = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public it.gov.pagopa.paymentupdater.dto.avro.message.Builder clearTimestamp() {
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    public message build() {
      try {
        message record = new message();
        record.op = fieldSetFlags()[0] ? this.op : (it.gov.pagopa.paymentupdater.dto.avro.MessageCrudOperation) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.senderServiceId = fieldSetFlags()[2] ? this.senderServiceId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.senderUserId = fieldSetFlags()[3] ? this.senderUserId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.timeToLiveSeconds = fieldSetFlags()[4] ? this.timeToLiveSeconds : (java.lang.Integer) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.lang.Long) defaultValue(fields()[5]);
        record.isPending = fieldSetFlags()[6] ? this.isPending : (java.lang.Boolean) defaultValue(fields()[6]);
        record.content_subject = fieldSetFlags()[7] ? this.content_subject : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.content_type = fieldSetFlags()[8] ? this.content_type : (it.gov.pagopa.paymentupdater.dto.avro.MessageContentType) defaultValue(fields()[8]);
        record.content_paymentData_amount = fieldSetFlags()[9] ? this.content_paymentData_amount : (java.lang.Integer) defaultValue(fields()[9]);
        record.content_paymentData_noticeNumber = fieldSetFlags()[10] ? this.content_paymentData_noticeNumber : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.content_paymentData_invalidAfterDueDate = fieldSetFlags()[11] ? this.content_paymentData_invalidAfterDueDate : (java.lang.Boolean) defaultValue(fields()[11]);
        record.content_paymentData_payeeFiscalCode = fieldSetFlags()[12] ? this.content_paymentData_payeeFiscalCode : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.timestamp = fieldSetFlags()[13] ? this.timestamp : (java.lang.Long) defaultValue(fields()[13]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
