/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.gov.pagopa.paymentupdater.dto.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MessageStatusCrudOperation {
  CREATE, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MessageStatusCrudOperation\",\"namespace\":\"it.gov.pagopa.reminder.dto\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
